name: book
channels:
  - pytorch
  - defaults
  - pyg
  - conda-forge
dependencies:
  - python
  - cudatoolkit
  - pytorch-scatter
  - pip
  - notebook
  - ipykernel
  - ipywidgets
  - git-lfs
  - libsndfile
  - pip:
      - -r requirements.txt
